GPUID: 0
WORKERS: 4
PRINT_FREQ: 100
SAVE_FREQ: 100
PIN_MEMORY: False
OUTPUT_DIR: 'output'
DISTRIBUTER: True
RANK: 0 # Rank of the current process. 
WORLD_SIZE: 1

CUDNN:
  BENCHMARK: True
  DETERMINISTIC: False
  ENABLED: True

DATASET:
  DATASET: OWN
  ROOT: "/home/repo/datasets/SynthText/100k_big_img"
  GT_FILE: {'train': 'gt.mat', 'val': ''}
  SCALE_FACTOR: 0.25
  ROT_FACTOR: 30
  STD: 0.193
  MEAN: 0.588

TRAIN:
  BATCH_SIZE_PER_GPU: 5
  SHUFFLE: True
  BEGIN_EPOCH: 0
  END_EPOCH: 2
  RESUME:
    IS_RESUME: False
    FILE: ''
  OPTIMIZER: 'adam'
  LR: 0.001
  WD: 0.0
  LR_STEP: [60, 80]
  LR_FACTOR: 1
  MOMENTUM: 0.0
  NESTEROV: False
  RMSPROP_ALPHA:
  RMSPROP_CENTERED:

TEST:
  BATCH_SIZE_PER_GPU: 100
  SHUFFLE: True
  NUM_TEST: 10
  NUM_TEST_DISP: 10

MODEL:
  NAME: 'craft'
  IMAGE_SIZE: 768
